LOAD DATA

INFILE 'ML_Labs.dat'
BADFILE 'ML_Labs.bad'
DISCARDFILE 'ML_Labs.dsc'

REPLACE

INTO TABLE NCI_LABS_MANUAL_LOAD_HOLD
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'
TRAILING NULLCOLS
(
PATIENT_ID,
LAB_SAMPLE_DATE_RAW,
LAB_SAMPLE_TIME_RAW,
LAB_TEST_NAME,
LAB_TEST_Result,
LAB_TEST_UOM,
LAB_TEST_RANGE,
LAB_TEST_EVENT,
RECEIVED_DATE SYSDATE,
RECORD_ID RECNUM
)
