Drop table OPS$BDL.NCI_LABS_MANUAL_LOAD_HOLD;

CREATE TABLE OPS$BDL.NCI_LABS_MANUAL_LOAD_HOLD
(
  Study                VARCHAR2(15),
  Patient_ID           VARCHAR2(10),
  OC_Patient_POS       VARCHAR2(12),
  LAB_SAMPLE_DATE_RAW  VARCHAR2(20),
  LAB_SAMPLE_TIME_RAW  VARCHAR2(20),
  LAB_TEST_NAME        VARCHAR2(200),
  LAB_TEST_Result      VARCHAR2(20),
  LAB_TEST_UOM         VARCHAR2(20),
  LAB_TEST_RANGE       VARCHAR2(80),
  LABORATORY           VARCHAR2(10),
  RECEIVED_DATE        DATE,
  RECORD_ID            NUMBER(10)
)
/

drop table OPS$BDL.NCI_LABS_MANUAL_LOAD_STAGE;

CREATE TABLE OPS$BDL.NCI_LABS_MANUAL_LOAD_STAGE
(
  Study                VARCHAR2(15),
  Patient_ID           VARCHAR2(10),
  OC_Patient_POS       VARCHAR2(12),
  LAB_SAMPLE_DATE_RAW  VARCHAR2(20),
  LAB_SAMPLE_TIME_RAW  VARCHAR2(20),
  LAB_TEST_NAME        VARCHAR2(200),
  LAB_TEST_Result      VARCHAR2(20),
  LAB_TEST_UOM         VARCHAR2(20),
  LAB_TEST_RANGE       VARCHAR2(80),
  LABORATORY           VARCHAR2(10),
  RECORD_ID            NUMBER(10),
  RECEIVED_DATE        DATE,
  LAB_SAMPLE_DATE      DATE,
  STAGE_DATE           Date,
  STAGE_USER           Varchar2(240),
  STAGE_NOTE           Varchar2(200),
  STAGE_ID             NUMBER(10),
  STATUS_FLAG          Varchar2(1),
  PROCESS_DATE         DATE,
  PROCESS_USER         Varchar2(240)
)
/


CREATE SEQUENCE OPS$BDL.NCI_MANUAL_LOAD_SEQ
  START WITH 1
  NOMAXVALUE
  MINVALUE 1
  NOCYCLE
  NOCACHE
  NOORDER;
  
-- UPCC Specific Coding
INSERT INTO NCI_LABS_MANUAL_LOAD_STAGE (
   STUDY, PATIENT_ID, OC_PATIENT_POS, 
   LAB_SAMPLE_DATE_RAW, LAB_SAMPLE_TIME_RAW, LAB_TEST_NAME, 
   LAB_TEST_RESULT, LAB_TEST_UOM, LAB_TEST_RANGE, 
   LABORATORY, RECORD_ID, RECEIVED_DATE, 
   LAB_SAMPLE_DATE, STAGE_DATE, 
   STAGE_USER, STAGE_NOTE, STAGE_ID, 
   STATUS_FLAG, PROCESS_DATE, PROCESS_USER) 
SELECT 'UPCC_07403', replace(PATIENT_ID,'-'), OC_PATIENT_POS, 
   LAB_SAMPLE_DATE_RAW, LAB_SAMPLE_TIME_RAW, LAB_TEST_NAME, 
   LAB_TEST_RESULT, LAB_TEST_UOM, LAB_TEST_RANGE, 
   'UPCC', RECORD_ID, RECEIVED_DATE, 
   to_date(LAB_SAMPLE_DATE_RAW||Lpad(LAB_SAMPLE_TIME_RAW,4,'0'),'YYYYMMDDHH24MI'), 
    sysdate, 
   user, 'Testing', NCI_MANUAL_LOAD_SEQ.nextval,
   'N', sysdate, user FROM NCI_LABS_MANUAL_LOAD_HOLD;

INSERT INTO NCI_LABS (
   RECORD_ID, 
   PATIENT_ID, 
   SAMPLE_DATETIME, 
   TEST_COMPONENT_ID, LABORATORY, LABTEST_NAME, 
   LAB_GRADE, RESULT, UNIT, 
   NORMAL_VALUE, PANEL_NAME, PATIENT_NAME, 
   COMMENTS, OC_LAB_PANEL, OC_LAB_QUESTION, 
   OC_LAB_EVENT, OC_PATIENT_POS, LOAD_DATE, 
   LOAD_FLAG, RECEIVED_DATE, DATE_CREATED, 
   DATE_MODIFIED, CREATED_BY, MODIFIED_BY, 
   TEST_CODE, CDW_RESULT_ID, OC_STUDY, 
   ERROR_REASON, OC_LAB_SUBSET, LOAD_MARK_DATE, 
   LOAD_MARK_USER) 
SELECT NULL Record_ID,
       PATIENT_ID,
       to_char(LAB_SAMPLE_DATE, 'MMDDYYHH24MI') SAMPLE_DATETIME,
       NULL TEST_COMPONENT_ID,
       LABORATORY,
       LAB_TEST_NAME LABTEST_NAME,
       NULL LAB_GRADE,
       LAB_TEST_RESULT RESULT,
       LAB_TEST_UOM UNIT,
       LAB_TEST_RANGE NORMAL_VALUE,
       NULL PANEL_NAME,
       NULL PATIENT_NAME,
       NULL COMMENTS, 
       NULL OC_LAB_PANEL, 
       NULL OC_LAB_QUESTION, 
       NULL OC_LAB_EVENT, 
       NULL OC_PATIENT_POS, 
       NULL LOAD_DATE, 
       'N'  LOAD_FLAG, 
       RECEIVED_DATE, 
       NULL DATE_CREATED, 
       NULL DATE_MODIFIED, 
       NULL CREATED_BY, 
       NULL MODIFIED_BY, 
       NULL TEST_CODE, 
       'ML-'||to_char(STAGE_ID)   CDW_RESULT_ID, 
       STUDY OC_STUDY, 
       NULL ERROR_REASON, 
       NULL OC_LAB_SUBSET, 
       NULL LOAD_MARK_DATE, 
       NULL LOAD_MARK_USER 
From NCI_LABS_MANUAL_LOAD_STAGE
where status_flag = 'N'

Update NCI_LABS_MANUAL_LOAD_STAGE
   set STATUS_flag = 'C'
 where status_flag = 'N'
   and exists (select 'x' from nci_labs
                where cdw_result_id = 'ML-'||stage_id);
   
select * from nci_labs where cdw_result_id like 'ML-%';   

commit;
