LOAD DATA

INFILE 'GTown_LabMap.dat'
BADFILE 'GTown_LabMap.bad'
DISCARDFILE 'GTown_LabMap.dsc'

append

INTO TABLE nci_lab_mapping
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'
TRAILING NULLCOLS
(
TEST_COMPONENT_ID, 
OC_LAB_QUESTION, 
TEST_CODE, 
LAB_TEST, 
LABORATORY
)
