
DROP TABLE NCI_LAB_VALID_PATIENTS CASCADE CONSTRAINTS
/

CREATE TABLE NCI_LAB_VALID_PATIENTS
(
  PT_ID        VARCHAR2(200 BYTE),
  PT           VARCHAR2(10 BYTE),
  STUDY        VARCHAR2(15 BYTE),
  NCI_INST_CD  VARCHAR2(200 BYTE),
  LABORATORY   VARCHAR2(10 BYTE)
)
/


CREATE INDEX NLVP_IDX2 ON NCI_LAB_VALID_PATIENTS
(STUDY)
/


CREATE INDEX NLVP_IDX3 ON NCI_LAB_VALID_PATIENTS
(PT_ID, LABORATORY)
/


CREATE INDEX NLVP_IDX1 ON NCI_LAB_VALID_PATIENTS
(PT_ID, NCI_INST_CD)
/


DROP PUBLIC SYNONYM NCI_LAB_VALID_PATIENTS
/

CREATE PUBLIC SYNONYM NCI_LAB_VALID_PATIENTS FOR NCI_LAB_VALID_PATIENTS
/


GRANT SELECT ON  NCI_LAB_VALID_PATIENTS TO LABLOADER
/

GRANT SELECT ON  NCI_LAB_VALID_PATIENTS TO LABLOADER_REVIEW
/

GRANT SELECT ON  NCI_LAB_VALID_PATIENTS TO LABLOADER_ADMIN
/


