ALTER TABLE NCI_LAB_LOAD_CTL ADD (USE_QUALIFY_VALUE          VARCHAR2(1));

COMMENT ON COLUMN NCI_LAB_LOAD_CTL.USE_QUALIFY_VALUE IS 'Set to ''Y'' to have study use QUALIFYING_VALUE from NCI_LABS, set to ''N'' to leave QUALIFYING_VALUE blank';

