CREATE PROFILE OCUSER_PROFILE 
    LIMIT CPU_PER_SESSION DEFAULT CPU_PER_CALL DEFAULT 
    CONNECT_TIME DEFAULT IDLE_TIME DEFAULT SESSIONS_PER_USER 
    DEFAULT LOGICAL_READS_PER_SESSION DEFAULT 
    LOGICAL_READS_PER_CALL DEFAULT PRIVATE_SGA DEFAULT 
    COMPOSITE_LIMIT DEFAULT FAILED_LOGIN_ATTEMPTS 3 
    PASSWORD_LOCK_TIME UNLIMITED PASSWORD_GRACE_TIME 30 
    PASSWORD_LIFE_TIME 180 PASSWORD_REUSE_MAX UNLIMITED 
    PASSWORD_REUSE_TIME 1800 PASSWORD_VERIFY_FUNCTION 
    PASSWORD_VERIFICATION;