--
--SQL Statement which produced this data:
--  Select * from NCI_UOM_MAIN
--
Insert into NCI_UOM_MAIN
   (VALUE, MEANING, TYPE_DISTANCE)
 Values
   ('dm', 'Decimeter', 'Distance');
Insert into NCI_UOM_MAIN
   (VALUE, MEANING, TYPE_DISTANCE)
 Values
   ('m', 'Meter', 'Distance');
Insert into NCI_UOM_MAIN
   (VALUE, MEANING, TYPE_DISTANCE)
 Values
   ('mcm', 'Micrometer', 'Distance');
Insert into NCI_UOM_MAIN
   (VALUE, MEANING, TYPE_DISTANCE)
 Values
   ('mm', 'Millimeter', 'Distance');
Insert into NCI_UOM_MAIN
   (VALUE, MEANING, TYPE_DISTANCE)
 Values
   ('nm', 'Nanometer', 'Distance');
Insert into NCI_UOM_MAIN
   (VALUE, MEANING, TYPE_DOSE)
 Values
   ('Seed', 'Seed', 'Dose');
Insert into NCI_UOM_MAIN
   (VALUE, MEANING, TYPE_DOSE)
 Values
   ('Gallon', 'Gallon  (Dose only)', 'Dose');
Insert into NCI_UOM_MAIN
   (VALUE, MEANING, TYPE_DOSE)
 Values
   ('Rad', 'Radiation absorbed dose (Rad)', 'Dose');
Insert into NCI_UOM_MAIN
   (VALUE, MEANING, TYPE_LABTEST)
 Values
   ('LPF', 'Per Low Power Field', 'Lab Test');
Insert into NCI_UOM_MAIN
   (VALUE, MEANING, TYPE_DOSE)
 Values
   ('mEq/hr', 'Milliequivalent per hour', 'Dose');
Insert into NCI_UOM_MAIN
   (VALUE, MEANING, TYPE_DOSE)
 Values
   ('mcg/hr', 'Microgram per hour', 'Dose');
Insert into NCI_UOM_MAIN
   (VALUE, MEANING, TYPE_DOSE)
 Values
   ('mg/hr', 'Milligram per hour', 'Dose');
Insert into NCI_UOM_MAIN
   (VALUE, MEANING, TYPE_DOSE)
 Values
   ('mg/wk', 'Milligram per week', 'Dose');
Insert into NCI_UOM_MAIN
   (VALUE, MEANING, TYPE_DOSE)
 Values
   ('mL/hr', 'Milliliter per hour', 'Dose');
Insert into NCI_UOM_MAIN
   (VALUE, MEANING, TYPE_DOSE)
 Values
   ('Patch', 'Patch', 'Dose');
Insert into NCI_UOM_MAIN
   (VALUE, MEANING, TYPE_DOSE)
 Values
   ('Session', 'Session', 'Dose');
Insert into NCI_UOM_MAIN
   (VALUE, MEANING, TYPE_LABTEST)
 Values
   ('IUnit/L', 'International unit per liter ', 'Lab Test');
Insert into NCI_UOM_MAIN
   (VALUE, MEANING, TYPE_DOSE)
 Values
   ('RE', 'Retinal equivalents', 'Dose');
Insert into NCI_UOM_MAIN
   (VALUE, MEANING, TYPE_DOSE)
 Values
   ('RAE', 'Vitamin A Retinol', 'Dose');
Insert into NCI_UOM_MAIN
   (VALUE, MEANING, TYPE_DOSE)
 Values
   ('IU Vit A', 'Vitamin A International unit', 'Dose');
Insert into NCI_UOM_MAIN
   (VALUE, MEANING, TYPE_DOSE)
 Values
   ('IU/mg A-TE', 'International units OR milligram alpha tocopherol', 'Dose');
Insert into NCI_UOM_MAIN
   (VALUE, MEANING, TYPE_LABTEST)
 Values
   ('EU/dL', 'Enzyme Units per deciliter', 'Lab Test');
Insert into NCI_UOM_MAIN
   (VALUE, MEANING, TYPE_LABTEST)
 Values
   ('EU', 'Enzyme Unit', 'Lab Test');
Insert into NCI_UOM_MAIN
   (VALUE, MEANING, TYPE_DOSE)
 Values
   ('mg/inh', 'Milligram per Inhalation', 'Dose');
Insert into NCI_UOM_MAIN
   (VALUE, MEANING, TYPE_LABTEST)
 Values
   ('/mm3', 'Per millimeter cubed', 'Lab Test');
Insert into NCI_UOM_MAIN
   (VALUE, MEANING, TYPE_DOSE)
 Values
   ('IV Bag', 'Intravenous bag', 'Dose');
Insert into NCI_UOM_MAIN
   (VALUE, MEANING, TYPE_LABTEST)
 Values
   ('%/100 WBC', 'Percent Per 100 WBC', 'Lab Test');
Insert into NCI_UOM_MAIN
   (VALUE, MEANING, TYPE_LABTEST)
 Values
   ('EU/mL', 'Enzyme Units per milliliter', 'Lab Test');
Insert into NCI_UOM_MAIN
   (VALUE, MEANING, TYPE_DOSE)
 Values
   ('AUC', 'Area under the curve', 'Dose');
Insert into NCI_UOM_MAIN
   (VALUE, MEANING, TYPE_LABTEST)
 Values
   ('pgPGE2/mg protein', 'Picogram of prostaglandin E2 (PGE2) per milligram', 'Lab Test');
Insert into NCI_UOM_MAIN
   (VALUE, MEANING, TYPE_LABTEST)
 Values
   ('nMol/mg protein', 'Nanomole per milligram of protein', 'Lab Test');
Insert into NCI_UOM_MAIN
   (VALUE, MEANING, TYPE_DOSE)
 Values
   ('10E6 Cell/kg', '10E6 Cells per kilogram', 'Dose');
Insert into NCI_UOM_MAIN
   (VALUE, MEANING, TYPE_DOSE)
 Values
   ('10E5 Cell/kg', '10E5 Cells per kilogram', 'Dose');
Insert into NCI_UOM_MAIN
   (VALUE, MEANING, TYPE_DOSE)
 Values
   ('10E4 Cell/kg', '10E4 Cells per kilogram', 'Dose');
Insert into NCI_UOM_MAIN
   (VALUE, MEANING, TYPE_LABTEST)
 Values
   ('NA', 'Not applicable; no UOM required', 'Lab Test');
Insert into NCI_UOM_MAIN
   (VALUE, MEANING, TYPE_LABTEST)
 Values
   ('10E7 Cell/kg', '10E7 Cells per kilogram', 'Lab Test');
Insert into NCI_UOM_MAIN
   (VALUE, MEANING, TYPE_DOSE)
 Values
   ('10E7 Cell/kg', '10E7 Cells per kilogram', 'Dose');
Insert into NCI_UOM_MAIN
   (VALUE, MEANING, TYPE_DOSE)
 Values
   ('Bottle', 'Bottle', 'Dose');
Insert into NCI_UOM_MAIN
   (VALUE, MEANING, TYPE_LABTEST)
 Values
   ('mcg/spec', 'Microgram per specimen', 'Lab Test');
Insert into NCI_UOM_MAIN
   (VALUE, MEANING, TYPE_LABTEST)
 Values
   ('/100 WBC', 'Per 100 identifiable White Blood cells', 'Lab Test');
Insert into NCI_UOM_MAIN
   (VALUE, MEANING, TYPE_LABTEST)
 Values
   ('CAE Unit', 'Complement activity enzyme (CAE) unit', 'Lab Test');
Insert into NCI_UOM_MAIN
   (VALUE, MEANING, TYPE_LABTEST)
 Values
   ('Titer', 'Antibody Titer', 'Lab Test');
Insert into NCI_UOM_MAIN
   (VALUE, MEANING, TYPE_LABTEST)
 Values
   ('RNA copies/mL', 'RNA copies per milliliter', 'Lab Test');
Insert into NCI_UOM_MAIN
   (VALUE, MEANING, TYPE_DOSE)
 Values
   ('mcg/m2', 'Microgram per meter squared', 'Dose');
Insert into NCI_UOM_MAIN
   (VALUE, MEANING, TYPE_DOSE)
 Values
   ('Unit/g', 'Unit per gram', 'Dose');
Insert into NCI_UOM_MAIN
   (VALUE, MEANING, TYPE_LABTEST)
 Values
   ('microU/mL', 'Microunit per milliliter', 'Lab Test');
Insert into NCI_UOM_MAIN
   (VALUE, MEANING, TYPE_LABTEST)
 Values
   ('GPL', 'IgG anti-cardiolipin antibodies', 'Lab Test');
Insert into NCI_UOM_MAIN
   (VALUE, MEANING, TYPE_LABTEST)
 Values
   ('MPL', 'IgM anti-cardiolipin antibodies', 'Lab Test');
Insert into NCI_UOM_MAIN
   (VALUE, MEANING, TYPE_LABTEST)
 Values
   ('L/sec', 'Liter per second', 'Lab Test');
Insert into NCI_UOM_MAIN
   (VALUE, MEANING, TYPE_LABTEST)
 Values
   ('mmol/min/kPa/L', 'Millimole per minute per thousand Pascal per Liter', 'Lab Test');
Insert into NCI_UOM_MAIN
   (VALUE, MEANING, TYPE_LABTEST)
 Values
   ('mL/minute/mmHg/L', 'Milliliter per minute per millimeter Hg per Liter', 'Lab Test');
Insert into NCI_UOM_MAIN
   (VALUE, MEANING, TYPE_DISTANCE)
 Values
   ('dm', 'Decimeter', 'Distance');
Insert into NCI_UOM_MAIN
   (VALUE, MEANING, TYPE_LABTEST)
 Values
   ('Index value', 'Index value', 'Lab Test');
Insert into NCI_UOM_MAIN
   (VALUE, MEANING, TYPE_DISTANCE)
 Values
   ('dm', 'Decimeter', 'Distance');
Insert into NCI_UOM_MAIN
   (VALUE, MEANING, TYPE_DISTANCE)
 Values
   ('dm', 'Decimeter', 'Distance');
Insert into NCI_UOM_MAIN
   (VALUE, MEANING, TYPE_DOSE, TYPE_LABTEST)
 Values
   ('mg/24hr', 'Milligram per 24 hours', 'Dose', 'Lab Test');
Insert into NCI_UOM_MAIN
   (VALUE, MEANING, TYPE_LABTEST)
 Values
   ('mg/L', 'Milligram per liter', 'Lab Test');
Insert into NCI_UOM_MAIN
   (VALUE, MEANING, TYPE_LABTEST)
 Values
   ('mg/mL/min', 'Milligram per milliliter per minute', 'Lab Test');
Insert into NCI_UOM_MAIN
   (VALUE, MEANING, TYPE_LABTEST)
 Values
   ('miu/mL', 'Milliinternational unit per milliliter', 'Lab Test');
Insert into NCI_UOM_MAIN
   (VALUE, MEANING, TYPE_LABTEST)
 Values
   ('mL/min', 'Milliliter per minute', 'Lab Test');
Insert into NCI_UOM_MAIN
   (VALUE, MEANING, TYPE_LABTEST)
 Values
   ('mL/min/1.73/BSA', 'Milliliter per minute times 1.73 times BSA', 'Lab Test');
Insert into NCI_UOM_MAIN
   (VALUE, MEANING, TYPE_LABTEST)
 Values
   ('mm3', 'Millimeter cubed', 'Lab Test');
Insert into NCI_UOM_MAIN
   (VALUE, MEANING, TYPE_LABTEST)
 Values
   ('mmHg', 'Millimeter of Mercury', 'Lab Test');
Insert into NCI_UOM_MAIN
   (VALUE, MEANING, TYPE_LABTEST)
 Values
   ('mm/hr', 'Millimeter per hour', 'Lab Test');
Insert into NCI_UOM_MAIN
   (VALUE, MEANING, TYPE_LABTEST)
 Values
   ('mmol/24hr', 'Millimole per 24 hours', 'Lab Test');
Insert into NCI_UOM_MAIN
   (VALUE, MEANING, TYPE_LABTEST)
 Values
   ('mmol/L', 'Millimole per Liter', 'Lab Test');
Insert into NCI_UOM_MAIN
   (VALUE, MEANING, TYPE_LABTEST)
 Values
   ('Million/microL', 'Million per microliter', 'Lab Test');
Insert into NCI_UOM_MAIN
   (VALUE, MEANING, TYPE_LABTEST)
 Values
   ('Million/mm3', 'Million per millimeter cubed', 'Lab Test');
Insert into NCI_UOM_MAIN
   (VALUE, MEANING, TYPE_LABTEST)
 Values
   ('MU/mL', 'Million units per milliliter', 'Lab Test');
Insert into NCI_UOM_MAIN
   (VALUE, MEANING, TYPE_LABTEST)
 Values
   ('mosmol/kg', 'Milliosmole per kilogram', 'Lab Test');
Insert into NCI_UOM_MAIN
   (VALUE, MEANING, TYPE_LABTEST)
 Values
   ('mL/minute/mmHg', 'Milliliter per minute per millimeters of Mercury', 'Lab Test');
Insert into NCI_UOM_MAIN
   (VALUE, MEANING, TYPE_LABTEST)
 Values
   ('ng/dL', 'Nanogram per deciliter', 'Lab Test');
Insert into NCI_UOM_MAIN
   (VALUE, MEANING, TYPE_DOSE, TYPE_LABTEST)
 Values
   ('ng/mL', 'Nanogram per milliliter', 'Dose', 'Lab Test');
Insert into NCI_UOM_MAIN
   (VALUE, MEANING, TYPE_LABTEST)
 Values
   ('ng/mL/hr', 'Nanogram per milliliter per hour', 'Lab Test');
Insert into NCI_UOM_MAIN
   (VALUE, MEANING, TYPE_LABTEST)
 Values
   ('nmol/L', 'Nanomole per Liter', 'Lab Test');
Insert into NCI_UOM_MAIN
   (VALUE, MEANING, TYPE_LABTEST)
 Values
   ('nmol/mL', 'Nanomole per milliliter', 'Lab Test');
Insert into NCI_UOM_MAIN
   (VALUE, MEANING, TYPE_DOSE, TYPE_LABTEST)
 Values
   ('%', 'Percent', 'Dose', 'Lab Test');
Insert into NCI_UOM_MAIN
   (VALUE, MEANING, TYPE_LABTEST)
 Values
   ('pg/dL', 'Picogram per deciliter', 'Lab Test');
Insert into NCI_UOM_MAIN
   (VALUE, MEANING, TYPE_LABTEST)
 Values
   ('pmol/L', 'Picomole per Liter', 'Lab Test');
Insert into NCI_UOM_MAIN
   (VALUE, MEANING, TYPE_LABTEST)
 Values
   ('pg/mL', 'Picrogram per milliliter', 'Lab Test');
Insert into NCI_UOM_MAIN
   (VALUE, MEANING, TYPE_LABTEST)
 Values
   ('Ratio', 'Ratio', 'Lab Test');
Insert into NCI_UOM_MAIN
   (VALUE, MEANING, TYPE_LABTEST)
 Values
   ('sec', 'Seconds', 'Lab Test');
Insert into NCI_UOM_MAIN
   (VALUE, MEANING, TYPE_LABTEST)
 Values
   ('Thousand/mm3', 'THOU/CMM', 'Lab Test');
Insert into NCI_UOM_MAIN
   (VALUE, MEANING, TYPE_LABTEST)
 Values
   ('Thousand/microL', 'THOU/MCL', 'Lab Test');
Insert into NCI_UOM_MAIN
   (VALUE, MEANING, TYPE_LABTEST)
 Values
   ('Thousand/microL', 'THOU/UL', 'Lab Test');
Insert into NCI_UOM_MAIN
   (VALUE, MEANING, TYPE_LABTEST)
 Values
   ('Thousand/microL', 'THOU/uL', 'Lab Test');
Insert into NCI_UOM_MAIN
   (VALUE, MEANING, TYPE_LABTEST)
 Values
   ('Thousand/mm3', 'Thous/CMM', 'Lab Test');
Insert into NCI_UOM_MAIN
   (VALUE, MEANING, TYPE_LABTEST)
 Values
   ('Thousand/microL', 'THOUS/MCL', 'Lab Test');
Insert into NCI_UOM_MAIN
   (VALUE, MEANING, TYPE_LABTEST)
 Values
   ('Thousand/microL', 'Thousand per microliter', 'Lab Test');
Insert into NCI_UOM_MAIN
   (VALUE, MEANING, TYPE_LABTEST)
 Values
   ('Thousand/mm3', 'Thousand per millimeter cubed', 'Lab Test');
Insert into NCI_UOM_MAIN
   (VALUE, MEANING, TYPE_LABTEST)
 Values
   ('Thousand/mm2', 'Thousand per millimeter squared', 'Lab Test');
Insert into NCI_UOM_MAIN
   (VALUE, MEANING, TYPE_LABTEST)
 Values
   ('Unit/24hr', 'Unit per 24 hours', 'Lab Test');
Insert into NCI_UOM_MAIN
   (VALUE, MEANING, TYPE_DOSE, TYPE_LABTEST)
 Values
   ('g', 'Gram', 'Dose', 'Lab Test');
Insert into NCI_UOM_MAIN
   (VALUE, MEANING, TYPE_DOSE, TYPE_LABTEST)
 Values
   ('mEq', 'Milliequivalent', 'Dose', 'Lab Test');
Insert into NCI_UOM_MAIN
   (VALUE, MEANING, TYPE_DOSE, TYPE_LABTEST)
 Values
   ('mEq/24hr', 'Milliequivalent per 24 hours', 'Dose', 'Lab Test');
Insert into NCI_UOM_MAIN
   (VALUE, MEANING, TYPE_DOSE, TYPE_LABTEST)
 Values
   ('mEq/dL', 'Milliequivalent per deciliter', 'Dose', 'Lab Test');
Insert into NCI_UOM_MAIN
   (VALUE, MEANING, TYPE_DOSE, TYPE_LABTEST)
 Values
   ('mEq/L', 'Milliequivalent per liter', 'Dose', 'Lab Test');
Insert into NCI_UOM_MAIN
   (VALUE, MEANING, TYPE_DOSE, TYPE_LABTEST)
 Values
   ('mg', 'Milligram', 'Dose', 'Lab Test');
Insert into NCI_UOM_MAIN
   (VALUE, MEANING, TYPE_DOSE, TYPE_LABTEST)
 Values
   ('mg/dL', 'Milligram per deciliter', 'Dose', 'Lab Test');
Insert into NCI_UOM_MAIN
   (VALUE, MEANING, TYPE_DOSE, TYPE_LABTEST)
 Values
   ('miu', 'Milliinternational unit', 'Dose', 'Lab Test');
Insert into NCI_UOM_MAIN
   (VALUE, MEANING, TYPE_DOSE, TYPE_LABTEST)
 Values
   ('miu/m2', 'Milliinternational unit per meter squared', 'Dose', 'Lab Test');
Insert into NCI_UOM_MAIN
   (VALUE, MEANING, TYPE_DOSE, TYPE_LABTEST)
 Values
   ('Million', 'Million', 'Dose', 'Lab Test');
Insert into NCI_UOM_MAIN
   (VALUE, MEANING, TYPE_DOSE, TYPE_LABTEST, TYPE_DISTANCE)
 Values
   ('No Srce', 'No source to enter', 'Dose', 'Lab Test', 'Distance');
Insert into NCI_UOM_MAIN
   (VALUE, MEANING, TYPE_DOSE, TYPE_LABTEST)
 Values
   ('pg', 'Picogram', 'Dose', 'Lab Test');
Insert into NCI_UOM_MAIN
   (VALUE, MEANING, TYPE_DOSE, TYPE_LABTEST)
 Values
   ('Thousand', 'Thousand', 'Dose', 'Lab Test');
Insert into NCI_UOM_MAIN
   (VALUE, MEANING, TYPE_DOSE, TYPE_LABTEST)
 Values
   ('Unit', 'Unit', 'Dose', 'Lab Test');
Insert into NCI_UOM_MAIN
   (VALUE, MEANING, TYPE_DOSE, TYPE_LABTEST, TYPE_DISTANCE)
 Values
   ('Unknown', 'Unknown', 'Dose', 'Lab Test', 'Distance');
Insert into NCI_UOM_MAIN
   (VALUE, MEANING, TYPE_DOSE)
 Values
   ('10E7 PFU', '10E7 Plaque Forming Units', 'Dose');
Insert into NCI_UOM_MAIN
   (VALUE, MEANING, TYPE_DOSE)
 Values
   ('10E8 PFU', '10E8 Plaque Forming Units', 'Dose');
Insert into NCI_UOM_MAIN
   (VALUE, MEANING, TYPE_DOSE)
 Values
   ('10E9 PFU', '10E9 Plaque Forming Units', 'Dose');
Insert into NCI_UOM_MAIN
   (VALUE, MEANING, TYPE_DOSE)
 Values
   ('Applcatn', 'Application', 'Dose');
Insert into NCI_UOM_MAIN
   (VALUE, MEANING, TYPE_DOSE)
 Values
   ('au', 'Atomic unit', 'Dose');
Insert into NCI_UOM_MAIN
   (VALUE, MEANING, TYPE_DOSE)
 Values
   ('bill PFU', 'Billion Plaque Forming Units', 'Dose');
Insert into NCI_UOM_MAIN
   (VALUE, MEANING, TYPE_DOSE)
 Values
   ('Caplet', 'Caplet', 'Dose');
Insert into NCI_UOM_MAIN
   (VALUE, MEANING, TYPE_DOSE)
 Values
   ('Capsule', 'Capsule', 'Dose');
Insert into NCI_UOM_MAIN
   (VALUE, MEANING, TYPE_DOSE)
 Values
   ('Cells', 'Cells', 'Dose');
Insert into NCI_UOM_MAIN
   (VALUE, MEANING, TYPE_DOSE)
 Values
   ('cGy', 'Centigray', 'Dose');
Insert into NCI_UOM_MAIN
   (VALUE, MEANING, TYPE_DOSE)
 Values
   ('Course', 'Course ', 'Dose');
Insert into NCI_UOM_MAIN
   (VALUE, MEANING, TYPE_DOSE)
 Values
   ('mL', 'Cubic centimeter (cc)', 'Dose');
Insert into NCI_UOM_MAIN
   (VALUE, MEANING, TYPE_DOSE)
 Values
   ('Ci', 'Curie', 'Dose');
Insert into NCI_UOM_MAIN
   (VALUE, MEANING, TYPE_DOSE)
 Values
   ('Course', 'Cycle', 'Dose');
Insert into NCI_UOM_MAIN
   (VALUE, MEANING, TYPE_DOSE)
 Values
   ('dL', 'Deciliter', 'Dose');
Insert into NCI_UOM_MAIN
   (VALUE, MEANING, TYPE_DOSE)
 Values
   ('Dose', 'Dose', 'Dose');
Insert into NCI_UOM_MAIN
   (VALUE, MEANING, TYPE_DOSE)
 Values
   ('gtts', 'Drops', 'Dose');
Insert into NCI_UOM_MAIN
   (VALUE, MEANING, TYPE_DOSE)
 Values
   ('Eq', 'Equivalent', 'Dose');
Insert into NCI_UOM_MAIN
   (VALUE, MEANING, TYPE_DOSE)
 Values
   ('Mole', 'Gram molecular weight (mole)', 'Dose');
Insert into NCI_UOM_MAIN
   (VALUE, MEANING, TYPE_DOSE)
 Values
   ('g/m2', 'Gram per meter squared', 'Dose');
Insert into NCI_UOM_MAIN
   (VALUE, MEANING, TYPE_DOSE)
 Values
   ('Gy', 'Gray', 'Dose');
Insert into NCI_UOM_MAIN
   (VALUE, MEANING, TYPE_DOSE)
 Values
   ('Hz', 'Hertz', 'Dose');
Insert into NCI_UOM_MAIN
   (VALUE, MEANING, TYPE_DOSE)
 Values
   ('Inhalatn', 'Inhalation', 'Dose');
Insert into NCI_UOM_MAIN
   (VALUE, MEANING, TYPE_DOSE, TYPE_LABTEST)
 Values
   ('Iunit', 'International unit', 'Dose', 'Lab Test');
Insert into NCI_UOM_MAIN
   (VALUE, MEANING, TYPE_DOSE)
 Values
   ('IUnit/kg', 'International unit per kilogram', 'Dose');
Insert into NCI_UOM_MAIN
   (VALUE, MEANING, TYPE_DOSE)
 Values
   ('IUnit/L', 'International unit per liter', 'Dose');
Insert into NCI_UOM_MAIN
   (VALUE, MEANING, TYPE_DOSE)
 Values
   ('Jcm2', 'Joules per centimeter squared', 'Dose');
Insert into NCI_UOM_MAIN
   (VALUE, MEANING, TYPE_DOSE)
 Values
   ('KeV', 'Kib-electron volt', 'Dose');
Insert into NCI_UOM_MAIN
   (VALUE, MEANING, TYPE_DOSE)
 Values
   ('kg', 'Kilogram', 'Dose');
Insert into NCI_UOM_MAIN
   (VALUE, MEANING, TYPE_DOSE)
 Values
   ('kHz', 'Kilohertz', 'Dose');
Insert into NCI_UOM_MAIN
   (VALUE, MEANING, TYPE_DOSE)
 Values
   ('kPa', 'Kilopascal', 'Dose');
Insert into NCI_UOM_MAIN
   (VALUE, MEANING, TYPE_DOSE)
 Values
   ('kU', 'Kilounit', 'Dose');
Insert into NCI_UOM_MAIN
   (VALUE, MEANING, TYPE_DOSE)
 Values
   ('kU/kg', 'Kilounit per kilogram', 'Dose');
Insert into NCI_UOM_MAIN
   (VALUE, MEANING, TYPE_DOSE, TYPE_LABTEST)
 Values
   ('kU/L', 'Kilounit per Liter', 'Dose', 'Lab Test');
Insert into NCI_UOM_MAIN
   (VALUE, MEANING, TYPE_DOSE, TYPE_LABTEST)
 Values
   ('L', 'Liter', 'Dose', 'Lab Test');
Insert into NCI_UOM_MAIN
   (VALUE, MEANING, TYPE_DOSE)
 Values
   ('Measure', 'Measure', 'Dose');
Insert into NCI_UOM_MAIN
   (VALUE, MEANING, TYPE_DOSE)
 Values
   ('MHz', 'Megahertz', 'Dose');
Insert into NCI_UOM_MAIN
   (VALUE, MEANING, TYPE_DOSE)
 Values
   ('Mrad', 'Megarad', 'Dose');
Insert into NCI_UOM_MAIN
   (VALUE, MEANING, TYPE_DOSE)
 Values
   ('MicroCi', 'MicroCurie', 'Dose');
Insert into NCI_UOM_MAIN
   (VALUE, MEANING, TYPE_DOSE)
 Values
   ('mcg', 'Microgram', 'Dose');
Insert into NCI_UOM_MAIN
   (VALUE, MEANING, TYPE_DOSE)
 Values
   ('mcg/cm2', 'Microgram per centimeter squared', 'Dose');
Insert into NCI_UOM_MAIN
   (VALUE, MEANING, TYPE_DOSE)
 Values
   ('mcg/kg', 'Microgram per kilogram', 'Dose');
Insert into NCI_UOM_MAIN
   (VALUE, MEANING, TYPE_DOSE, TYPE_LABTEST)
 Values
   ('microL', 'Microliter', 'Dose', 'Lab Test');
Insert into NCI_UOM_MAIN
   (VALUE, MEANING, TYPE_DOSE)
 Values
   ('micromol', 'Micromole', 'Dose');
Insert into NCI_UOM_MAIN
   (VALUE, MEANING, TYPE_DOSE)
 Values
   ('mCi', 'Millicurie', 'Dose');
Insert into NCI_UOM_MAIN
   (VALUE, MEANING, TYPE_DOSE, TYPE_LABTEST)
 Values
   ('mg/kg', 'Milligram per kilogram', 'Dose', 'Lab Test');
Insert into NCI_UOM_MAIN
   (VALUE, MEANING, TYPE_DOSE)
 Values
   ('mg/m2', 'Milligram per meter squared', 'Dose');
Insert into NCI_UOM_MAIN
   (VALUE, MEANING, TYPE_DOSE, TYPE_LABTEST)
 Values
   ('mg/mL', 'Milligram per milliliter', 'Dose', 'Lab Test');
Insert into NCI_UOM_MAIN
   (VALUE, MEANING, TYPE_DOSE)
 Values
   ('mL/kg', 'Milliliter per kilogram', 'Dose');
Insert into NCI_UOM_MAIN
   (VALUE, MEANING, TYPE_DOSE, TYPE_LABTEST)
 Values
   ('mmol', 'Millimole', 'Dose', 'Lab Test');
Insert into NCI_UOM_MAIN
   (VALUE, MEANING, TYPE_DOSE)
 Values
   ('MeV', 'Million electron volt', 'Dose');
Insert into NCI_UOM_MAIN
   (VALUE, MEANING, TYPE_DOSE, TYPE_LABTEST)
 Values
   ('mill PFU', 'Million Plaque Forming Units', 'Dose', 'Lab Test');
Insert into NCI_UOM_MAIN
   (VALUE, MEANING, TYPE_DOSE)
 Values
   ('MU', 'Million units  ', 'Dose');
Insert into NCI_UOM_MAIN
   (VALUE, MEANING, TYPE_DOSE)
 Values
   ('MVP', 'Million Viral Particles', 'Dose');
Insert into NCI_UOM_MAIN
   (VALUE, MEANING, TYPE_DOSE)
 Values
   ('mosmol', 'Milliosmole', 'Dose');
Insert into NCI_UOM_MAIN
   (VALUE, MEANING, TYPE_DOSE, TYPE_LABTEST)
 Values
   ('mL', 'Milliter', 'Dose', 'Lab Test');
Insert into NCI_UOM_MAIN
   (VALUE, MEANING, TYPE_DOSE)
 Values
   ('millunit', 'Milliunit', 'Dose');
Insert into NCI_UOM_MAIN
   (VALUE, MEANING, TYPE_DOSE)
 Values
   ('mV', 'Millivolt', 'Dose');
Insert into NCI_UOM_MAIN
   (VALUE, MEANING, TYPE_DOSE)
 Values
   ('nCi', 'Nanocurie', 'Dose');
Insert into NCI_UOM_MAIN
   (VALUE, MEANING, TYPE_DOSE)
 Values
   ('ng', 'Nanogram', 'Dose');
Insert into NCI_UOM_MAIN
   (VALUE, MEANING, TYPE_DOSE)
 Values
   ('ng/kg', 'Nanogram per kilogram', 'Dose');
Insert into NCI_UOM_MAIN
   (VALUE, MEANING, TYPE_DOSE)
 Values
   ('ng/L', 'Nanogram per Liter', 'Dose');
Insert into NCI_UOM_MAIN
   (VALUE, MEANING, TYPE_DOSE)
 Values
   ('nm light', 'Nanometer of Light', 'Dose');
Insert into NCI_UOM_MAIN
   (VALUE, MEANING, TYPE_DOSE)
 Values
   ('nmol', 'Nanomole  ', 'Dose');
Insert into NCI_UOM_MAIN
   (VALUE, MEANING, TYPE_DOSE)
 Values
   ('osmol', 'Osmolality', 'Dose');
Insert into NCI_UOM_MAIN
   (VALUE, MEANING, TYPE_DOSE)
 Values
   ('oz', 'Ounce', 'Dose');
Insert into NCI_UOM_MAIN
   (VALUE, MEANING, TYPE_DOSE)
 Values
   ('packet', 'Packet', 'Dose');
Insert into NCI_UOM_MAIN
   (VALUE, MEANING, TYPE_DOSE)
 Values
   ('Pa', 'Pascal', 'Dose');
Insert into NCI_UOM_MAIN
   (VALUE, MEANING, TYPE_DOSE)
 Values
   ('PFU', 'Plaque Forming Units', 'Dose');
Insert into NCI_UOM_MAIN
   (VALUE, MEANING, TYPE_DOSE)
 Values
   ('psi', 'Pounds per square inch', 'Dose');
Insert into NCI_UOM_MAIN
   (VALUE, MEANING, TYPE_DOSE)
 Values
   ('puff', 'Puff', 'Dose');
Insert into NCI_UOM_MAIN
   (VALUE, MEANING, TYPE_DOSE)
 Values
   ('Spray', 'Spray', 'Dose');
Insert into NCI_UOM_MAIN
   (VALUE, MEANING, TYPE_DOSE)
 Values
   ('Suppstry', 'Suppository', 'Dose');
Insert into NCI_UOM_MAIN
   (VALUE, MEANING, TYPE_DOSE)
 Values
   ('Tbsp', 'Tablespoon', 'Dose');
Insert into NCI_UOM_MAIN
   (VALUE, MEANING, TYPE_DOSE)
 Values
   ('Tablet', 'Tablet', 'Dose');
Insert into NCI_UOM_MAIN
   (VALUE, MEANING, TYPE_DOSE)
 Values
   ('tsp', 'Teaspoon', 'Dose');
Insert into NCI_UOM_MAIN
   (VALUE, MEANING, TYPE_DOSE)
 Values
   ('TCID', 'Tissue Culture Infections Dose', 'Dose');
Insert into NCI_UOM_MAIN
   (VALUE, MEANING, TYPE_DOSE)
 Values
   ('Troche', 'Troche', 'Dose');
Insert into NCI_UOM_MAIN
   (VALUE, MEANING, TYPE_DOSE)
 Values
   ('Unit/kg', 'Unit per kilogram', 'Dose');
Insert into NCI_UOM_MAIN
   (VALUE, MEANING, TYPE_DOSE)
 Values
   ('VP', 'Viral Particles', 'Dose');
Insert into NCI_UOM_MAIN
   (VALUE, MEANING, TYPE_LABTEST)
 Values
   ('Thousand/microL', '1000/microL', 'Lab Test');
Insert into NCI_UOM_MAIN
   (VALUE, MEANING, TYPE_LABTEST)
 Values
   ('Thousand/mm2', '1000/mm2', 'Lab Test');
Insert into NCI_UOM_MAIN
   (VALUE, MEANING, TYPE_LABTEST)
 Values
   ('Thousand/mm3', '1000/mm3', 'Lab Test');
Insert into NCI_UOM_MAIN
   (VALUE, MEANING, TYPE_LABTEST)
 Values
   ('10E12 Cells/L', '10E12 Cells per Liter', 'Lab Test');
Insert into NCI_UOM_MAIN
   (VALUE, MEANING, TYPE_LABTEST)
 Values
   ('10E3 Cells/microL', '10E3 Cells per microLiter', 'Lab Test');
Insert into NCI_UOM_MAIN
   (VALUE, MEANING, TYPE_LABTEST)
 Values
   ('10E6 Cells', '10E6 Cells', 'Lab Test');
Insert into NCI_UOM_MAIN
   (VALUE, MEANING, TYPE_LABTEST)
 Values
   ('10E6 Cells/microL', '10E6 Cells per microLiter', 'Lab Test');
Insert into NCI_UOM_MAIN
   (VALUE, MEANING, TYPE_LABTEST)
 Values
   ('10E6 Cells/mm3', '10E6 Cells per millimeter cubed', 'Lab Test');
Insert into NCI_UOM_MAIN
   (VALUE, MEANING, TYPE_LABTEST)
 Values
   ('10E8 Cells', '10E8 Cells', 'Lab Test');
Insert into NCI_UOM_MAIN
   (VALUE, MEANING, TYPE_LABTEST)
 Values
   ('10E9 Cells', '10E9 Cells', 'Lab Test');
Insert into NCI_UOM_MAIN
   (VALUE, MEANING, TYPE_LABTEST)
 Values
   ('10E9 Cells/L', '10E9 Cells per Liter', 'Lab Test');
Insert into NCI_UOM_MAIN
   (VALUE, MEANING, TYPE_LABTEST)
 Values
   ('Cells/microL', 'Cells per microliter', 'Lab Test');
Insert into NCI_UOM_MAIN
   (VALUE, MEANING, TYPE_LABTEST)
 Values
   ('Copies', 'Copies', 'Lab Test');
Insert into NCI_UOM_MAIN
   (VALUE, MEANING, TYPE_LABTEST)
 Values
   ('cubic microns', 'CU MIC', 'Lab Test');
Insert into NCI_UOM_MAIN
   (VALUE, MEANING, TYPE_LABTEST)
 Values
   ('cubic microns', 'CU MICR', 'Lab Test');
Insert into NCI_UOM_MAIN
   (VALUE, MEANING, TYPE_LABTEST)
 Values
   ('cubic microns', 'CU MICRON', 'Lab Test');
Insert into NCI_UOM_MAIN
   (VALUE, MEANING, TYPE_LABTEST)
 Values
   ('cubic microns', 'Cubic microns', 'Lab Test');
Insert into NCI_UOM_MAIN
   (VALUE, MEANING, TYPE_LABTEST)
 Values
   ('fL', 'Femtoliter', 'Lab Test');
Insert into NCI_UOM_MAIN
   (VALUE, MEANING, TYPE_LABTEST)
 Values
   ('g/24hr', 'Gram per 24 hours', 'Lab Test');
Insert into NCI_UOM_MAIN
   (VALUE, MEANING, TYPE_LABTEST)
 Values
   ('g/dL', 'Gram per deciliter', 'Lab Test');
Insert into NCI_UOM_MAIN
   (VALUE, MEANING, TYPE_LABTEST)
 Values
   ('g/L', 'Gram per liter', 'Lab Test');
Insert into NCI_UOM_MAIN
   (VALUE, MEANING, TYPE_LABTEST)
 Values
   ('g/microL', 'Gram per microliter', 'Lab Test');
Insert into NCI_UOM_MAIN
   (VALUE, MEANING, TYPE_LABTEST)
 Values
   ('HPF', 'Per High Power Field', 'Lab Test');
Insert into NCI_UOM_MAIN
   (VALUE, MEANING, TYPE_LABTEST)
 Values
   ('IUnit/m2', 'International unit per meter squared', 'Lab Test');
Insert into NCI_UOM_MAIN
   (VALUE, MEANING, TYPE_LABTEST)
 Values
   ('IUnit/mL', 'International unit per milliliter', 'Lab Test');
Insert into NCI_UOM_MAIN
   (VALUE, MEANING, TYPE_LABTEST)
 Values
   ('IUnit/mL', 'IU/mL', 'Lab Test');
Insert into NCI_UOM_MAIN
   (VALUE, MEANING, TYPE_LABTEST)
 Values
   ('Thousand/mm3', 'K/cmm', 'Lab Test');
Insert into NCI_UOM_MAIN
   (VALUE, MEANING, TYPE_LABTEST)
 Values
   ('Thousand/microL', 'K/microL', 'Lab Test');
Insert into NCI_UOM_MAIN
   (VALUE, MEANING, TYPE_LABTEST)
 Values
   ('Thousand/mm2', 'K/mm2', 'Lab Test');
Insert into NCI_UOM_MAIN
   (VALUE, MEANING, TYPE_LABTEST)
 Values
   ('Thousand/mm3', 'K/mm3', 'Lab Test');
Insert into NCI_UOM_MAIN
   (VALUE, MEANING, TYPE_LABTEST)
 Values
   ('Thousand/microL', 'K/UL', 'Lab Test');
Insert into NCI_UOM_MAIN
   (VALUE, MEANING, TYPE_LABTEST)
 Values
   ('Thousand/microL', 'K/ul', 'Lab Test');
Insert into NCI_UOM_MAIN
   (VALUE, MEANING, TYPE_LABTEST)
 Values
   ('Thousand/microL', 'K/uL', 'Lab Test');
Insert into NCI_UOM_MAIN
   (VALUE, MEANING, TYPE_DOSE, TYPE_LABTEST)
 Values
   ('L/min', 'Liters per minute', 'Dose', 'Lab Test');
Insert into NCI_UOM_MAIN
   (VALUE, MEANING, TYPE_LABTEST)
 Values
   ('Million/mm3', 'M/cmm', 'Lab Test');
Insert into NCI_UOM_MAIN
   (VALUE, MEANING, TYPE_LABTEST)
 Values
   ('Million/microL', 'M/mcL', 'Lab Test');
Insert into NCI_UOM_MAIN
   (VALUE, MEANING, TYPE_LABTEST)
 Values
   ('Million/microL', 'M/microL', 'Lab Test');
Insert into NCI_UOM_MAIN
   (VALUE, MEANING, TYPE_LABTEST)
 Values
   ('Million/mm3', 'M/mm3', 'Lab Test');
Insert into NCI_UOM_MAIN
   (VALUE, MEANING, TYPE_LABTEST)
 Values
   ('Million/mm3', 'M/MM3', 'Lab Test');
Insert into NCI_UOM_MAIN
   (VALUE, MEANING, TYPE_LABTEST)
 Values
   ('Million/microL', 'M/Ul', 'Lab Test');
Insert into NCI_UOM_MAIN
   (VALUE, MEANING, TYPE_LABTEST)
 Values
   ('Million/microL', 'M/uL', 'Lab Test');
Insert into NCI_UOM_MAIN
   (VALUE, MEANING, TYPE_LABTEST)
 Values
   ('Million/microL', 'M/ul', 'Lab Test');
Insert into NCI_UOM_MAIN
   (VALUE, MEANING, TYPE_LABTEST)
 Values
   ('microIU/mL', 'Micro International Unit per milliliter', 'Lab Test');
Insert into NCI_UOM_MAIN
   (VALUE, MEANING, TYPE_LABTEST)
 Values
   ('mcg/24hr', 'Microgram per 24 hours', 'Lab Test');
Insert into NCI_UOM_MAIN
   (VALUE, MEANING, TYPE_LABTEST)
 Values
   ('mcg/dL', 'Microgram per deciliter', 'Lab Test');
Insert into NCI_UOM_MAIN
   (VALUE, MEANING, TYPE_LABTEST)
 Values
   ('mcg/L', 'Microgram per Liter', 'Lab Test');
Insert into NCI_UOM_MAIN
   (VALUE, MEANING, TYPE_LABTEST)
 Values
   ('mcg/mL', 'Microgram per milliliter', 'Lab Test');
Insert into NCI_UOM_MAIN
   (VALUE, MEANING, TYPE_LABTEST)
 Values
   ('micromol/24hr', 'Micromole per 24 hours', 'Lab Test');
Insert into NCI_UOM_MAIN
   (VALUE, MEANING, TYPE_LABTEST)
 Values
   ('micromol/dL', 'Micromole per deciliter', 'Lab Test');
Insert into NCI_UOM_MAIN
   (VALUE, MEANING, TYPE_LABTEST)
 Values
   ('micromol/L', 'Micromole per liter', 'Lab Test');
Insert into NCI_UOM_MAIN
   (VALUE, MEANING, TYPE_LABTEST)
 Values
   ('Million/microL', 'Mil/Ul', 'Lab Test');
Insert into NCI_UOM_MAIN
   (VALUE, MEANING, TYPE_LABTEST)
 Values
   ('Million/mm3', 'MILL/CMM', 'Lab Test');
Insert into NCI_UOM_MAIN
   (VALUE, MEANING, TYPE_LABTEST)
 Values
   ('Million/microL', 'MILL/MCL', 'Lab Test');
Insert into NCI_UOM_MAIN
   (VALUE, MEANING, TYPE_LABTEST)
 Values
   ('mEq/kg', 'Milliequivalent per kilogram', 'Lab Test');
Insert into NCI_UOM_MAIN
   (VALUE, MEANING, TYPE_LABTEST)
 Values
   ('Unit/L', 'Unit per Liter', 'Lab Test');
Insert into NCI_UOM_MAIN
   (VALUE, MEANING, TYPE_DOSE, TYPE_LABTEST)
 Values
   ('Unit/m2', 'Unit per meter squared', 'Dose', 'Lab Test');
Insert into NCI_UOM_MAIN
   (VALUE, MEANING, TYPE_LABTEST)
 Values
   ('Unit/mL', 'Unit per millilliter', 'Lab Test');
Insert into NCI_UOM_MAIN
   (VALUE, MEANING, TYPE_LABTEST)
 Values
   ('Unit/mm3', 'Unit per millimeters cubed', 'Lab Test');
Insert into NCI_UOM_MAIN
   (VALUE, MEANING, TYPE_DISTANCE)
 Values
   ('cm', 'Centimeter', 'Distance');
COMMIT;
