CREATE TABLE NCI_STUDY_PATIENT_IDS_CTL
(
  OC_STUDY                VARCHAR2(15 BYTE),
  PATIENT_ID_DCM_NAME     VARCHAR2(16 BYTE),
  PATIENT_ID_QUEST_NAME   VARCHAR2(20 BYTE),
  NCI_INST_CD_DCM_NAME    VARCHAR2(16 BYTE),
  NCI_INST_CD_QUEST_NAME  VARCHAR2(20 BYTE),
  NCI_INST_CD_CONST       VARCHAR2(30 BYTE),
  CREATE_DATE             DATE                  DEFAULT SYSDATE,
  CREATE_USER             VARCHAR2(30 BYTE)     DEFAULT USER,
  MODIFY_DATE             DATE,
  MODIFY_USER             VARCHAR2(30 BYTE)
)
TABLESPACE &&USERS_TABLESPACE;


CREATE INDEX NSPI_IDX ON NCI_STUDY_PATIENT_IDS
(OC_STUDY, OC_PATIENT_POS, REPEAT_SN)
TABLESPACE &&USERS_TABLESPACE;


