-- drop table first
DROP TABLE NCI_LABS_MANUAL_LOAD_STAGE;

-- create table
CREATE TABLE NCI_LABS_MANUAL_LOAD_STAGE
(
  STUDY                VARCHAR2(15 BYTE),
  PATIENT_ID           VARCHAR2(10 BYTE),
  OC_PATIENT_POS       VARCHAR2(12 BYTE),
  LAB_SAMPLE_DATE_RAW  VARCHAR2(20 BYTE),
  LAB_SAMPLE_TIME_RAW  VARCHAR2(20 BYTE),
  LAB_TEST_NAME        VARCHAR2(200 BYTE),
  LAB_TEST_RESULT      VARCHAR2(20 BYTE),
  LAB_TEST_UOM         VARCHAR2(20 BYTE),
  LAB_TEST_RANGE       VARCHAR2(80 BYTE),
  LABORATORY           VARCHAR2(10 BYTE),
  RECORD_ID            NUMBER(10),
  RECEIVED_DATE        DATE,
  LAB_SAMPLE_DATE      DATE,
  STAGE_DATE           DATE,
  STAGE_USER           VARCHAR2(240 BYTE),
  STAGE_NOTE           VARCHAR2(200 BYTE),
  STAGE_ID             NUMBER(10),
  STATUS_FLAG          VARCHAR2(1 BYTE),
  PROCESS_DATE         DATE,
  PROCESS_USER         VARCHAR2(240 BYTE),
  LAB_TEST_EVENT       VARCHAR2(40 BYTE),
  BATCH_ID             NUMBER,
  LAB_TEST_RANGE_LOW   VARCHAR2(30 BYTE),
  LAB_TEST_RANGE_HIGH  VARCHAR2(30 BYTE),
  QUALIFYING_VALUE     VARCHAR2(80 BYTE),
  STATUS_COMMENT       VARCHAR2(200 BYTE)       DEFAULT 'New Record'
)
TABLESPACE USERS
PCTUSED    40
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          128K
            NEXT             128K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
NOMONITORING;

COMMENT ON COLUMN NCI_LABS_MANUAL_LOAD_STAGE.LAB_TEST_EVENT IS 'This column holds the CPE (Event) as assigned by the investigator.';

COMMENT ON COLUMN NCI_LABS_MANUAL_LOAD_STAGE.QUALIFYING_VALUE IS 'Used to pass QUALIFYING_VALUE to the DCM in C3D';

GRANT DELETE, INSERT, SELECT, UPDATE ON  NCI_LABS_MANUAL_LOAD_STAGE TO C3PR;

