
--
-- BDL_RESPONSE_REPEATS  (Table) 
--
CREATE TABLE BDL_RESPONSE_REPEATS
(
  REPEAT_SN      NUMBER(10),
  DATE_CREATED   DATE,
  DATE_MODIFIED  DATE,
  CREATED_BY     VARCHAR2(240 BYTE),
  MODIFIED_BY    VARCHAR2(240 BYTE)
)
TABLESPACE  &&USERS_TABLESPACE;


--
-- BRT_BRI_SEQ  (Trigger) 
--
CREATE OR REPLACE TRIGGER BRT_BRI_SEQ
 BEFORE INSERT
 ON BDL_RESPONSE_REPEATS 
 FOR EACH ROW
BEGIN

   if :new.CREATED_BY IS NULL THEN
   :new.CREATED_BY := user;
   END IF;
   :new.DATE_CREATED := sysdate;
END;
/
SHOW ERRORS;



--
-- BRT_BRU_SEQ  (Trigger) 
--
CREATE OR REPLACE TRIGGER BRT_BRU_SEQ
 BEFORE UPDATE
 ON BDL_RESPONSE_REPEATS 
 FOR EACH ROW
BEGIN

    :new.MODIFIED_BY  := user;
    :new.DATE_MODIFIED := sysdate;
END;
/
SHOW ERRORS;




