--
-- BDL_TEMP_FILES  (Table) 
--
CREATE TABLE BDL_TEMP_FILES
(
  ID                VARCHAR2(20 BYTE),
  INVESTIGATOR      VARCHAR2(10 BYTE),
  SITE              VARCHAR2(10 BYTE),
  PATIENT           VARCHAR2(10 BYTE),
  DOCUMENT_NO       VARCHAR2(20 BYTE),
  PLANNED_EVENT     VARCHAR2(30 BYTE),
  SUBEVENT_NO       NUMBER(2),
  DCI_DATE          VARCHAR2(50 BYTE),
  DCI_TIME          VARCHAR2(6 BYTE),
  DCI_NAME          VARCHAR2(50 BYTE),
  DCM_NAME          VARCHAR2(50 BYTE),
  DCM_SUBSET        VARCHAR2(50 BYTE),
  DCM_QUESGRP       VARCHAR2(50 BYTE),
  DCM_QUES          VARCHAR2(50 BYTE),
  DCM_OCCUR         NUMBER(3),
  REPEAT_SN         NUMBER(4),
  VALUETEXT         VARCHAR2(200 BYTE),
  DATA_COMMENT      VARCHAR2(200 BYTE),
  QUALIFYING_VALUE  VARCHAR2(100 BYTE),
  STUDY             VARCHAR2(50 BYTE),
  DATE_CREATED      DATE,
  DATE_MODIFIED     DATE,
  CREATED_BY        VARCHAR2(240 BYTE),
  MODIFIED_BY       VARCHAR2(240 BYTE)
)
TABLESPACE &&USERS_TABLESPACE;

--
-- BTE_BRI_SEQ  (Trigger) 
--
CREATE OR REPLACE TRIGGER BTE_BRI_SEQ
 BEFORE INSERT
 ON BDL_TEMP_FILES 
 FOR EACH ROW
BEGIN

   if :new.CREATED_BY IS NULL THEN
   :new.CREATED_BY := user;
   END IF;
   :new.DATE_CREATED := sysdate;
END;
/
SHOW ERRORS;


--
-- BTE_BRU_SEQ  (Trigger) 
--
CREATE OR REPLACE TRIGGER BTE_BRU_SEQ
 BEFORE UPDATE
 ON BDL_TEMP_FILES 
 FOR EACH ROW
BEGIN

    :new.MODIFIED_BY  := user;
    :new.DATE_MODIFIED := sysdate;
END;
/
SHOW ERRORS;


