--
-- MDLABS_HOLD  (Table) 
--
CREATE TABLE MDLABS_HOLD
(
  PROTOCOL              VARCHAR2(20 BYTE),
  ACCESSIONNUMBER       VARCHAR2(10 BYTE),
  OBX_OBSERVATIONDTIME  VARCHAR2(50 BYTE),
  LAB_NAME              VARCHAR2(50 BYTE),
  PROCEDURENAME         VARCHAR2(50 BYTE),
  OBSERVATIONVALUE      VARCHAR2(50 BYTE),
  UNITS                 VARCHAR2(20 BYTE),
  REFERENCERANGE        VARCHAR2(20 BYTE)
)
TABLESPACE  &&USERS_TABLESPACE;



