CREATE TABLE MIS_PROT_PAT_CDRLIST
(
  PROTOCOLID      VARCHAR2(10 BYTE)             NOT NULL,
  MPI             VARCHAR2(10 BYTE)             NOT NULL,
  MRN             VARCHAR2(10 BYTE),
  LASTNAME        VARCHAR2(25 BYTE),
  MIDDLEINITIAL   VARCHAR2(15 BYTE),
  FIRSTNAME       VARCHAR2(25 BYTE),
  SUFFIX          VARCHAR2(15 BYTE),
  PATIENTMISNAME  VARCHAR2(80 BYTE)
)
TABLESPACE &&USERS_TABLESPACE;

