--
-- NCI_LABS_ERROR_LABS  (Table) 
--
CREATE TABLE NCI_LABS_ERROR_LABS
(
  OC_STUDY       VARCHAR2(15 BYTE),
  PATIENT_ID     VARCHAR2(10 BYTE),
  ERROR_REASON   VARCHAR2(200 BYTE),
  CYCLE          VARCHAR2(100 BYTE),
  DATE_CREATED   DATE,
  DATE_MODIFIED  DATE,
  CREATED_BY     VARCHAR2(30 BYTE),
  MODIFIED_BY    VARCHAR2(30 BYTE)
)
TABLESPACE &&USERS_TABLESPACE;

--
-- NLB_BI  (Trigger) 
--
CREATE OR REPLACE TRIGGER NLB_BI
 BEFORE INSERT
 ON NCI_LABS_ERROR_LABS 
  FOR EACH ROW
-- PL/SQL BLOCK
BEGIN

 if :new.CREATED_BY IS NULL THEN
   :new.CREATED_BY := user;
 END IF;
 :new.DATE_CREATED := sysdate;
END;
/
SHOW ERRORS;


--
-- NLB_BU  (Trigger) 
--
CREATE OR REPLACE TRIGGER NLB_BU
 BEFORE UPDATE
 ON NCI_LABS_ERROR_LABS 
 FOR EACH ROW
BEGIN

    :new.MODIFIED_BY  := user;
    :new.DATE_MODIFIED := sysdate;
END;
/
SHOW ERRORS;

