CREATE TABLE NCI_STUDY_PATIENT_IDS
(
  OC_STUDY         VARCHAR2(15 BYTE),
  OC_PATIENT_POS   VARCHAR2(12 BYTE),
  PT_ID_FUL        VARCHAR2(30 BYTE),
  NCI_INST_CD_FUL  VARCHAR2(30 BYTE),
  REPEAT_SN        NUMBER(3)
)
TABLESPACE &&USERS_TABLESPACE;

