--
-- NCI_LABS_MANUAL_LOAD_STAGE  (Table) 
--
CREATE TABLE NCI_LABS_MANUAL_LOAD_STAGE
(
  STUDY                VARCHAR2(15 BYTE),
  PATIENT_ID           VARCHAR2(10 BYTE),
  OC_PATIENT_POS       VARCHAR2(12 BYTE),
  LAB_SAMPLE_DATE_RAW  VARCHAR2(20 BYTE),
  LAB_SAMPLE_TIME_RAW  VARCHAR2(20 BYTE),
  LAB_TEST_NAME        VARCHAR2(200 BYTE),
  LAB_TEST_RESULT      VARCHAR2(20 BYTE),
  LAB_TEST_UOM         VARCHAR2(20 BYTE),
  LAB_TEST_RANGE       VARCHAR2(80 BYTE),
  LABORATORY           VARCHAR2(10 BYTE),
  RECORD_ID            NUMBER(10),
  RECEIVED_DATE        DATE,
  LAB_SAMPLE_DATE      DATE,
  STAGE_DATE           DATE,
  STAGE_USER           VARCHAR2(240 BYTE),
  STAGE_NOTE           VARCHAR2(200 BYTE),
  STAGE_ID             NUMBER(10),
  STATUS_FLAG          VARCHAR2(1 BYTE),
  PROCESS_DATE         DATE,
  PROCESS_USER         VARCHAR2(240 BYTE)
)
TABLESPACE &&USERS_TABLESPACE;



