CREATE TABLE BTRIS_LAB_INVALID_VALUES
(
  ATTRIBUTE    VARCHAR2(30 BYTE)                NOT NULL,
  VALUE        VARCHAR2(30 BYTE)                NOT NULL,
  CREATE_USER  VARCHAR2(30 BYTE),
  CREATE_DATE  DATE,
  MODIFY_USER  VARCHAR2(30 BYTE),
  MODIFY_DATE  DATE
)
/

CREATE OR REPLACE TRIGGER BLIV_BI_TRG 
 BEFORE INSERT 
 ON BTRIS_LAB_INVALID_VALUES 
 REFERENCING OLD AS OLD NEW AS NEW 
 FOR EACH ROW 
-- PL/SQL Block
BEGIN 
 IF :NEW.CREATE_USER IS NULL THEN 
   :NEW.CREATE_USER := USER; 
 END IF; 
 :NEW.CREATE_DATE := SYSDATE; 
END;
/

SHOW ERRORS;

CREATE OR REPLACE TRIGGER BLIV_BU_TRG 
 BEFORE UPDATE 
 ON BTRIS_LAB_INVALID_VALUES 
 REFERENCING OLD AS OLD NEW AS NEW 
 FOR EACH ROW 
-- PL/SQL Block
BEGIN 
 IF :NEW.MODIFY_USER IS NULL THEN 
   :NEW.MODIFY_USER := USER; 
 END IF; 
 :NEW.MODIFY_DATE := SYSDATE; 
END;
/

SHOW ERRORS;



