CREATE TABLE BTRIS_PROTOCOL_STATUS
(
  C3D_STUDY    VARCHAR2(30 BYTE)                NOT NULL,
  BTRIS_STUDY  VARCHAR2(30 BYTE),
  STATUS       VARCHAR2(10 BYTE)                NOT NULL
)
/


