CREATE TABLE BTRIS_LAB_TEST_NAMES
(
  BTRIS_LAB_TEST_ID  VARCHAR2(8 BYTE),
  LAB_TEST_NAME      VARCHAR2(200 BYTE),
  LABTEST_CODE       VARCHAR2(30 BYTE),
  LAB_UNIT           VARCHAR2(30 BYTE),
  LAB_RANGE          VARCHAR2(30 BYTE),
  FIRST_REPORT_DATE  VARCHAR2(30 BYTE),
  LAST_REPORT_DATE   VARCHAR2(30 BYTE),
  CREATE_DATE        DATE,
  CREATE_USER        VARCHAR2(30 BYTE)
)
/


CREATE OR REPLACE TRIGGER BLTN_BI_TRG
BEFORE INSERT 
 ON BTRIS_LAB_TEST_NAMES 
 REFERENCING OLD AS OLD NEW AS NEW 
 FOR EACH ROW 
-- PL/SQL Block
BEGIN 
 IF :NEW.CREATE_USER IS NULL THEN 
   :NEW.CREATE_USER := USER; 
 END IF; 
 :NEW.CREATE_DATE := SYSDATE; 
END;
/

SHOW ERRORS;