INSERT INTO NCI_LAB_LOAD_CTL ( OC_STUDY, OFF_STUDY_OFFSET_DAYS, STOP_LAB_LOAD_FLAG, DATE_CREATED,
DATE_MODIFIED, CREATED_BY, MODIFIED_BY, OFF_STUDY_DCM, OFF_STUDY_QUEST, LOAD_OTHER_LABS, LABORATORY,
BLANK_PRESTUDY_USE_ENROLL, REVIEW_STUDY, LABTESTNAME_IS_OCLABQUEST, PRESTUDY_LAB_DATE_DCM,
PRESTUDY_LAB_DATE_QUEST, PRESTUDY_OFFSET_DAYS, DATE_CHECK_CODE, ENROLLMENT_DATE_DCM,
ENROLLMENT_DATE_QUEST ) VALUES ( 
'ALL', 0, 'N',  Sysdate,  NULL, USER, NULL, 'OFF STUDY SUMM', 'OFF_STDY_DT', 'N', 'CDW', 'N', 'N', 'N'
, 'ENROLLMENT', 'PRESTUDY_LAB_DATE', 0, 'BOTH', 'ENROLLMENT', 'REG_DT'); 

INSERT INTO NCI_LAB_LOAD_CTL ( OC_STUDY, OFF_STUDY_OFFSET_DAYS, STOP_LAB_LOAD_FLAG, DATE_CREATED,
DATE_MODIFIED, CREATED_BY, MODIFIED_BY, OFF_STUDY_DCM, OFF_STUDY_QUEST, LOAD_OTHER_LABS, LABORATORY,
BLANK_PRESTUDY_USE_ENROLL, REVIEW_STUDY, LABTESTNAME_IS_OCLABQUEST, PRESTUDY_LAB_DATE_DCM,
PRESTUDY_LAB_DATE_QUEST, PRESTUDY_OFFSET_DAYS, DATE_CHECK_CODE, ENROLLMENT_DATE_DCM,
ENROLLMENT_DATE_QUEST ) VALUES ( 
'LAB_LOADER', 0, 'N',  Sysdate,  NULL, USER, NULL, 'OFF STUDY SUMM', 'OFF_STDY_DT', 'Y', 
'CDW', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL); 

commit;
 
