-- Drop table first
DROP TABLE NCI_LABS_AUTOLOAD_HOLD;

-- Create table 
CREATE TABLE NCI_LABS_AUTOLOAD_HOLD
(
  STUDY          VARCHAR2(15 BYTE),
  CREATE_DATE    DATE,
  CREATE_USER    VARCHAR2(30 BYTE),
  RESTART_DATE   DATE,
  RESTART_COUNT  NUMBER(6),
  REQUESTS       NUMBER(6)
)
TABLESPACE USERS
PCTUSED    40
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          128K
            NEXT             128K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
NOMONITORING;

