--
-- NCI_UOM_MAIN  (Table) 
--
CREATE TABLE NCI_UOM_MAIN
(
  VALUE          VARCHAR2(30 BYTE),
  MEANING        VARCHAR2(50 BYTE),
  TYPE_DOSE      VARCHAR2(4 BYTE),
  TYPE_LABTEST   VARCHAR2(10 BYTE),
  TYPE_DISTANCE  VARCHAR2(10 BYTE)
);

--
-- NCI_UOM_MAIN_LOG  (Table) 
--
CREATE TABLE NCI_UOM_MAIN_LOG
(
  OLD_VALUE    VARCHAR2(20 BYTE),
  OLD_MEANING  VARCHAR2(200 BYTE),
  NEW_VALUE    VARCHAR2(20 BYTE),
  NEW_MEANING  VARCHAR2(200 BYTE),
  CHANGED_BY   VARCHAR2(30 BYTE),
  CHANGE_TYPE  CHAR(1 BYTE),
  TIMESTAMP    DATE
);

--
-- AUDIT_NCI_UOM_MAIN  (Trigger) 
--
CREATE OR REPLACE TRIGGER AUDIT_NCI_UOM_MAIN
AFTER INSERT OR DELETE OR UPDATE ON
NCI_UOM_MAIN FOR EACH ROW
DECLARE
  v_ChangeType CHAR(1);
 BEGIN
    IF INSERTING THEN
    v_ChangeType := 'I';
  ELSIF UPDATING THEN
    v_ChangeType := 'U';
  ELSE
    v_ChangeType := 'D';
  END IF;

  INSERT INTO NCI_UOM_MAIN_LOG
    (change_type, changed_by, timestamp,
 OLD_VALUE,
 OLD_MEANING,
 NEW_VALUE,
 NEW_MEANING
  )
  VALUES
    (v_ChangeType, USER, SYSDATE,
  :OLD.VALUE,
  :OLD.MEANING,
  :NEW.VALUE,
  :NEW.MEANING
    );

 END audit_NCI_UOM_MAIN;
/
SHOW ERRORS;
