
SET TIME OFF
SET HEADING ON
SET LINESIZE 120
SET PAGESIZE 52
SET TRIMOUT OFF
SET TRIMSPOOL OFF
SET PAUSE OFF
SET WRAP OFF
SET ECHO OFF
SET DOCUMENT OFF
SET VERIFY OFF
SET SHOW OFF
SET FEEDBACK OFF
SET ARRAYSIZE 15
SET NUMWIDTH 10

COLUMN today            NOPRINT NEW_VALUE     datevar

COLUMN 	INSERTED_DATE			HEADING "INSERTED DATE"	FORMAT A20

SELECT TO_CHAR(SYSDATE,'DD-MON-YY HH:MI:SS AM') today FROM DUAL;

SPOOL CDW_LAST_LOAD_DATA;

DEFINE studytitle =  "LAB_LOADER - CDW_LAST_LOAD_DATA"
DEFINE filename = "File: CDW_LAST_LOAD_DATA"
DEFINE Progname = "SQl script: CDW_LAST_LOAD_DATA.SQL"
TTITLE LEFT 'User: ' SQL.USER CENTER studytitle RIGHT datevar SKIP 2
BTITLE LEFT filename          CENTER progname   RIGHT 'Page:' FORMAT 09 SQL.PNO 

Select
  INSERTED_DATE
from CDW_LAST_LOAD;

SPOOL OFF;

CLEAR COLUMNS


