
SET TIME OFF
SET HEADING ON
SET LINESIZE 140
SET PAGESIZE 52
SET TRIMOUT OFF
SET TRIMSPOOL OFF
SET PAUSE OFF
SET WRAP OFF
SET ECHO OFF
SET DOCUMENT OFF
SET VERIFY OFF
SET SHOW OFF
SET FEEDBACK OFF
SET ARRAYSIZE 15
SET NUMWIDTH 10

COLUMN today            NOPRINT NEW_VALUE     datevar



COLUMN 	OC_LAB_QUESTION			HEADING "NCI_LABS - OC LAB QUESTION"	FORMAT A30
COLUMN 	NAME				HEADING "LABTEST - NAME"		FORMAT A20
COLUMN 	QUESTION_STATUS_CODE		HEADING "QST STATUS CODE"		FORMAT A20


SELECT TO_CHAR(SYSDATE,'DD-MON-YY HH:MI:SS AM') today FROM DUAL;

SPOOL LABTESTS_DATA;

DEFINE studytitle =  "LAB_LOADER - Verify NCI OC_LAB QUESTIONS ARE LISTED IN LABTESTS VW"
DEFINE filename = "File: LABTESTS_DATA"
DEFINE Progname = "SQl script: LABTESTS_DATA.SQL"
TTITLE LEFT 'User: ' SQL.USER CENTER studytitle RIGHT datevar SKIP 2
BTITLE LEFT filename          CENTER progname   RIGHT 'Page:' FORMAT 09 SQL.PNO 

Select distinct
    a.OC_LAB_QUESTION,
    b.NAME,
    b.QUESTION_STATUS_CODE
from
NCI_LABS a,
LABTESTS b
WHERE a.OC_LAB_QUESTION = b.NAME
order by a.OC_LAB_QUESTION;

SPOOL OFF;

CLEAR COLUMNS

