
SET TIME OFF
SET HEADING ON
SET LINESIZE 120
SET PAGESIZE 52
SET TRIMOUT OFF
SET TRIMSPOOL OFF
SET PAUSE OFF
SET WRAP OFF
SET ECHO OFF
SET DOCUMENT OFF
SET VERIFY OFF
SET SHOW OFF
SET FEEDBACK OFF
SET ARRAYSIZE 15
SET NUMWIDTH 10

COLUMN today            NOPRINT NEW_VALUE     datevar

COLUMN 	OC_STUDY 			HEADING "OC STUDY"		FORMAT A20
COLUMN 	OC_PATIENT_POS			HEADING "OC PATIENT POSITION"	FORMAT A20
COLUMN 	PT_ID_FUL			HEADING "PATIENT ID (LAB)"	FORMAT A20
COLUMN 	NCI_INST_CD_FUL			HEADING "NCI INSTITUTION"	FORMAT A20
COLUMN 	REPEAT_SN			HEADING "REPEAT SN"		


SELECT TO_CHAR(SYSDATE,'DD-MON-YY HH:MI:SS AM') today FROM DUAL;

SPOOL NCI_STUDY_PATIENT_IDS_DATA;

DEFINE studytitle =  "LAB_LOADER - NCI_STUDY_PATIENT_IDS"
DEFINE filename = "File: NCI_STUDY_PATIENT_IDS_DATA"
DEFINE Progname = "SQl script: NCI_STUDY_PATIENT_IDS_DATA.SQL"
TTITLE LEFT 'User: ' SQL.USER CENTER studytitle RIGHT datevar SKIP 2
BTITLE LEFT filename          CENTER progname   RIGHT 'Page:' FORMAT 09 SQL.PNO 

Select
  OC_STUDY,
  PT_ID_FUL,
  OC_PATIENT_POS, 
  NCI_INST_CD_FUL,
  REPEAT_SN
from NCI_STUDY_PATIENT_IDS
ORDER BY 1, 2, 3;

SPOOL OFF;

CLEAR COLUMNS


