
SET TIME OFF
SET HEADING ON
SET LINESIZE 140
SET PAGESIZE 52
SET TRIMOUT OFF
SET TRIMSPOOL OFF
SET PAUSE OFF
SET WRAP OFF
SET ECHO OFF
SET DOCUMENT OFF
SET VERIFY OFF
SET SHOW OFF
SET FEEDBACK OFF
SET ARRAYSIZE 15
SET NUMWIDTH 10

COLUMN today            NOPRINT NEW_VALUE     datevar


COLUMN 	OC_STUDY			HEADING "NCI_LABS - OC STUDY"		FORMAT A20
COLUMN 	OC_LAB_QUESTION			HEADING "NCI_LABS - OC LAB QUESTION"	FORMAT A30
COLUMN 	DCM_NAME			HEADING "DCM NAME"			FORMAT A15
COLUMN 	CPE_NAME			HEADING "CPE NAME"			FORMAT A15
COLUMN 	SUBSET_NAME			HEADING "SUBSET NAME"			FORMAT A15
COLUMN 	CPE_NAME			HEADING "CPE NAME"			FORMAT A15
COLUMN 	QUESTION_NAME			HEADING "QUESTION NAME"			FORMAT A15


SELECT TO_CHAR(SYSDATE,'DD-MON-YY HH:MI:SS AM') today FROM DUAL;

SPOOL NCI_LABS_NCI_STUDY_LABDCM_EVENTS;

DEFINE studytitle =  "LAB_LOADER - NCI_LABS linked to NCI_STUDY_LABDCM_EVENTS_TB"
DEFINE filename = "File: NCI_LABS_NCI_STUDY_LABDCM_EVENTS"
DEFINE Progname = "SQl script: NCI_LABS_NCI_STUDY_LABDCM_EVENTS.SQL"
TTITLE LEFT 'User: ' SQL.USER CENTER studytitle RIGHT datevar SKIP 2
BTITLE LEFT filename          CENTER progname   RIGHT 'Page:' FORMAT 09 SQL.PNO 

Select
    a.OC_STUDY,
    a.OC_LAB_QUESTION,
    b.DCM_NAME,
    b.CPE_NAME,
    b.SUBSET_NAME,
    b.QUESTION_NAME
from
NCI_LABS a,
NCI_STUDY_LABDCM_EVENTS_TB b
WHERE a.OC_STUDY = b.STUDY AND a.OC_LAB_QUESTION = b.OC_LAB_QUESTION
order by a.OC_LAB_QUESTION;

SPOOL OFF;

CLEAR COLUMNS

