REM CLEAR SCREEN

SET TIME OFF
SET HEADING ON
SET LINESIZE 125
SET PAGESIZE 52
SET TRIMOUT OFF
SET TRIMSPOOL OFF
SET PAUSE OFF
SET WRAP OFF
SET ECHO OFF
SET DOCUMENT OFF
SET VERIFY OFF
SET SHOW OFF
SET FEEDBACK OFF
SET NUMWIDTH 10

REM PRC Added 

COLUMN today            		NOPRINT NEW_VALUE     		datevar

COLUMN 	PATIENT_ID			HEADING "PATIENT ID"		FORMAT A10
COLUMN 	CDW_RESULT_ID			HEADING "RESULT ID"		FORMAT A12
COLUMN 	LABTEST_NAME			HEADING "LABTEST NAME"		FORMAT A15
COLUMN 	SAMPLE_DATETIME			HEADING "SAMPLE DATETIME"	FORMAT A15
COLUMN 	RECEIVED_DATE			HEADING "RECEIVED DATE"		FORMAT A15
COLUMN 	DATE_CREATED			HEADING "DATE CREATED"		FORMAT A15
COLUMN 	DATE_MODIFIED			HEADING "DATE MODIFIED"		FORMAT A15
COLUMN 	LOAD_MARK_DATE			HEADING "LOAD MARK DATE"	FORMAT A15
COLUMN 	LOAD_MARK_USER			HEADING "LOAD MARK USER"	FORMAT A15
COLUMN 	LOAD_FLAG			HEADING "LOAD FLAG"		FORMAT A10
COLUMN 	ERROR_REASON			HEADING "ERROR REASON"		FORMAT A50 WRAP

SELECT TO_CHAR(SYSDATE,'DD-MON-YY') today FROM DUAL;

ACCEPT PTID PROMPT "Enter Patient ID: "

SPOOL NCI_LABS_ERRORS_&PTID;

DEFINE studytitle =  "LAB LOADER - NCI_LABS ERRORS &&PTID"
DEFINE filename = "File: NCI_LABS_ERRORS_PTID"
DEFINE Progname = "SQl script: NCI_LABS_ERRORS_PTID.SQL"
TTITLE LEFT 'User: ' SQL.USER CENTER studytitle RIGHT datevar SKIP 2
BTITLE LEFT filename          CENTER progname   RIGHT 'Page:' FORMAT 09 SQL.PNO 

Select 
  CDW_RESULT_ID,
  SAMPLE_DATETIME,
  LABTEST_NAME,
  LOAD_FLAG,
  ERROR_REASON
from NCI_LABS
where ERROR_REASON is not NULL and PATIENT_ID = '&PTID'
order by 1,2, 3;
spool off;

CLEAR COLUMNS

/


