
SET TIME OFF
SET HEADING ON
SET LINESIZE 100
SET PAGESIZE 52
SET TRIMOUT OFF
SET TRIMSPOOL OFF
SET PAUSE OFF
SET WRAP OFF
SET ECHO OFF
SET DOCUMENT OFF
SET VERIFY OFF
SET SHOW OFF
SET FEEDBACK OFF
SET ARRAYSIZE 15
SET NUMWIDTH 10

COLUMN today            NOPRINT NEW_VALUE     datevar


COLUMN 	PATIENT_ID			HEADING "PATIENT ID"		FORMAT A10
COLUMN 	SAMPLE_DATETIME			HEADING "SAMPLE DATETIME"	FORMAT A15
COLUMN 	RECEIVED_DATE			HEADING "RECEIVED DATE"		FORMAT A15
COLUMN 	DATE_CREATED			HEADING "DATE CREATED"		FORMAT A15
COLUMN 	LABTEST_NAME			HEADING "LABTEST"		FORMAT A15
COLUMN 	OC_LAB_QUESTION			HEADING "OC LAB QST"		FORMAT A15
COLUMN 	LOAD_MARK_DATE			HEADING "LD MARK DT"		FORMAT A10
COLUMN 	LOAD_MARK_USER			HEADING "LOAD MARK USER"	FORMAT A15
COLUMN 	LOAD_FLAG			HEADING "LOAD FL"		FORMAT A7
COLUMN 	ERROR_REASON			HEADING "ERROR"			FORMAT A25 WRAP
COLUMN 	RESNUM				HEADING "# RECORDS"		

SELECT TO_CHAR(SYSDATE,'DD-MON-YY HH:MI:SS AM') today FROM DUAL;

SPOOL NCI_LABS_LOAD_FLAG_SUM;

DEFINE studytitle =  "LAB_LOADER - NCI_LABS - LOAD FLAG SUMMARY"
DEFINE filename = "File: NCI_LABS_LOAD_FLAG_SUM"
DEFINE Progname = "SQl script: NCI_LABS_LOAD_FLAG_SUM.SQL"
TTITLE LEFT 'User: ' SQL.USER CENTER studytitle RIGHT datevar SKIP 2
BTITLE LEFT filename          CENTER progname   RIGHT 'Page:' FORMAT 09 SQL.PNO 


Select
  PATIENT_ID,
  LOAD_FLAG,
  count(CDW_RESULT_ID) RESNUM
from NCI_LABS
group by
  PATIENT_ID,
  LOAD_FLAG
order by
  PATIENT_ID,
  LOAD_FLAG;

SPOOL OFF;

CLEAR COLUMNS

