UPDATE NCI_LAB_LOAD_CTL 
SET
DATE_CHECK_CODE = NULL,
BLANK_PRESTUDY_USE_ENROLL = NULL
WHERE OC_STUDY = 'LAB_LOADER';

UPDATE NCI_LAB_LOAD_CTL 
SET
BLANK_PRESTUDY_USE_ENROLL = NULL,
OFF_STUDY_OFFSET_DAYS = NULL
WHERE OC_STUDY = 'ALL';

commit;
 
