UPDATE NCI_LAB_LOAD_CTL 
SET
LABTESTNAME_IS_OCLABQUEST = 'Y'
WHERE OC_STUDY = 'LAB_LOADER';

UPDATE NCI_LAB_LOAD_CTL 
SET
LABTESTNAME_IS_OCLABQUEST = 'N'
WHERE OC_STUDY = 'ALL';

commit;
 
