
SET TIME OFF
SET HEADING ON
SET LINESIZE 120
SET PAGESIZE 52
SET TRIMOUT OFF
SET TRIMSPOOL OFF
SET PAUSE OFF
SET WRAP OFF
SET ECHO OFF
SET DOCUMENT OFF
SET VERIFY OFF
SET SHOW OFF
SET FEEDBACK OFF
SET ARRAYSIZE 15
SET NUMWIDTH 10

COLUMN today            NOPRINT NEW_VALUE     datevar

COLUMN 	OC_STUDY 			HEADING "OC STUDY"		FORMAT A12
COLUMN 	PATIENT_ID_DCM_NAME		HEADING "PID DCM"		FORMAT A12
COLUMN 	PATIENT_ID_QUEST_NAME		HEADING "PID QST"		FORMAT A12
COLUMN 	NCI_INST_CD_DCM_NAME		HEADING "INST DCM"		FORMAT A12
COLUMN 	NCI_INST_CD_QUEST_NAME		HEADING "INST QST"		FORMAT A12
COLUMN 	NCI_INST_CD_CONST		HEADING "INST CONST"		FORMAT A12
COLUMN  LABORATORY			HEADING "LAB"			FORMAT A5
COLUMN  STOP_LAB_LOAD_FLAG		HEADING "STOP LOAD"		FORMAT A12
COLUMN  LOAD_OTHER_LABS			HEADING "LOAD OTHER"		FORMAT A12
COLUMN  REVIEW_STUDY			HEADING "REVIEW"		FORMAT A8
COLUMN  LABTESTNAME_IS_OCLABQUEST	HEADING "TESTNAME"		FORMAT A8
COLUMN  DATE_CHECK_CODE			HEADING "DATE CHKCD"		FORMAT A12
COLUMN  ENROLLMENT_DATE_DCM		HEADING "ENROLLDT DCM"		FORMAT A12
COLUMN  ENROLLMENT_DATE_QUEST		HEADING "ENROLLDT QST"		FORMAT A12
COLUMN  PRESTUDY_LAB_DATE_DCM		HEADING "PREST DT DCM"		FORMAT A12
COLUMN  PRESTUDY_LAB_DATE_QUEST		HEADING "PREST DT QST"		FORMAT A12
COLUMN  PRESTUDY_OFFSET_DAYS		HEADING "OFFSETDAYS"		
COLUMN  BLANK_PRESTUDY_USE_ENROLL	HEADING "USE ENROLLDT"		FORMAT A12
COLUMN  OFF_STUDY_DCM			HEADING "OFFST DCM"		FORMAT A15
COLUMN  OFF_STUDY_QUEST			HEADING "OFFST QST"		FORMAT A12

SELECT TO_CHAR(SYSDATE,'DD-MON-YY HH:MI:SS AM') today FROM DUAL;

SPOOL NCI_STUDY_PATIENT_IDS_CTL;

DEFINE studytitle =  "LAB_LOADER - CONFIGURATION VALUES - NCI_STUDY_PATIENT_IDS_CTL"
DEFINE filename = "File: NCI_STUDY_PATIENT_IDS_CTL"
DEFINE Progname = "SQl script: NCI_STUDY_PATIENT_IDS_CTL.SQL"
TTITLE LEFT 'User: ' SQL.USER CENTER studytitle RIGHT datevar SKIP 2
BTITLE LEFT filename          CENTER progname   RIGHT 'Page:' FORMAT 09 SQL.PNO 

Select
  OC_STUDY,
  PATIENT_ID_DCM_NAME,
  PATIENT_ID_QUEST_NAME,
  NCI_INST_CD_DCM_NAME,
  NCI_INST_CD_QUEST_NAME,
  NCI_INST_CD_CONST
from NCI_STUDY_PATIENT_IDS_CTL;

SPOOL OFF;

CLEAR COLUMNS


