UPDATE NCI_LAB_LOAD_CTL 
SET
OFF_STUDY_OFFSET_DAYS = NULL,
STOP_LAB_LOAD_FLAG = NULL,
OFF_STUDY_DCM = NULL,
OFF_STUDY_QUEST = NULL,
LOAD_OTHER_LABS = 'Y',
BLANK_PRESTUDY_USE_ENROLL = NULL,
REVIEW_STUDY = NULL,
LABTESTNAME_IS_OCLABQUEST = 'N',
PRESTUDY_LAB_DATE_DCM = NULL,
PRESTUDY_LAB_DATE_QUEST = NULL,
PRESTUDY_OFFSET_DAYS = NULL,
DATE_CHECK_CODE = NULL,
ENROLLMENT_DATE_DCM = NULL,
ENROLLMENT_DATE_QUEST =  NULL
WHERE OC_STUDY = 'LAB_LOADER';

UPDATE NCI_LAB_LOAD_CTL 
SET
OFF_STUDY_OFFSET_DAYS = 3,
STOP_LAB_LOAD_FLAG = 'N',
OFF_STUDY_DCM = 'OFF TREATMT STDY',
OFF_STUDY_QUEST = 'OFF_STDY_DT',
LOAD_OTHER_LABS = 'N',
BLANK_PRESTUDY_USE_ENROLL = 'N',
REVIEW_STUDY = 'N',
LABTESTNAME_IS_OCLABQUEST = 'Y',
PRESTUDY_LAB_DATE_DCM = 'ENROLLMENT',
PRESTUDY_LAB_DATE_QUEST = 'PRESTUDY_LAB_DATE',
PRESTUDY_OFFSET_DAYS = 10,
DATE_CHECK_CODE = 'BOTH',
ENROLLMENT_DATE_DCM = 'ENROLLMENT',
ENROLLMENT_DATE_QUEST = 'REG_DT'
WHERE OC_STUDY = 'ALL';

commit;
 
