
SET TIME OFF
SET HEADING ON
SET LINESIZE 140
SET PAGESIZE 52
SET TRIMOUT OFF
SET TRIMSPOOL OFF
SET PAUSE OFF
SET WRAP OFF
SET ECHO OFF
SET DOCUMENT OFF
SET VERIFY OFF
SET SHOW OFF
SET FEEDBACK OFF
SET ARRAYSIZE 15
SET NUMWIDTH 10

COLUMN today            NOPRINT NEW_VALUE     datevar

COLUMN 	UNIT		HEADING "NCI_LABS UNIT"		FORMAT A20
COLUMN 	VALUE		HEADING "NCI_UOMS UNIT"		FORMAT A20

SELECT TO_CHAR(SYSDATE,'DD-MON-YY HH:MI:SS AM') today FROM DUAL;

SPOOL NCI_LABS_NCI_UOMS;

DEFINE studytitle =  "LAB_LOADER - NCI_LABS - UNIT OF MEASURE SHOULD BE LISTED IN NCI_UOMS VW"
DEFINE filename = "File: NCI_LABS_NCI_UOMS"
DEFINE Progname = "SQl script: NCI_LABS_NCI_UOMS.SQL"
TTITLE LEFT 'User: ' SQL.USER CENTER studytitle RIGHT datevar SKIP 2
BTITLE LEFT filename          CENTER progname   RIGHT 'Page:' FORMAT 09 SQL.PNO 


Select distinct a.unit, b.value
from NCI_LABS a, NCI_UOMS b
where a.unit = b.value;


SPOOL OFF;


CLEAR COLUMNS

