
SET TIME OFF
SET HEADING ON
SET LINESIZE 140
SET PAGESIZE 52
SET TRIMOUT OFF
SET TRIMSPOOL OFF
SET PAUSE OFF
SET WRAP OFF
SET ECHO OFF
SET DOCUMENT OFF
SET VERIFY OFF
SET SHOW OFF
SET FEEDBACK OFF
SET ARRAYSIZE 15
SET NUMWIDTH 10

COLUMN today            NOPRINT NEW_VALUE     datevar


COLUMN 	LABORATORY			HEADING "LABORATORY"		FORMAT A15
COLUMN 	TEST_COMPONENT_ID		HEADING "TEST COMPONENT ID"	FORMAT A20
COLUMN 	OC_LAB_QUESTION			HEADING "OC LAB QUESTION"	FORMAT A20
COLUMN 	LAB_PANEL			HEADING "LAB PANEL"		FORMAT A20


SELECT TO_CHAR(SYSDATE,'DD-MON-YY HH:MI:SS AM') today FROM DUAL;

SPOOL NCI_LAB_MAPPING_DATA;

DEFINE studytitle =  "LAB_LOADER - NCI_LAB_MAPPING"
DEFINE filename = "File: NCI_LAB_MAPPING_DATA"
DEFINE Progname = "SQl script: NCI_LAB_MAPPING_DATA.SQL"
TTITLE LEFT 'User: ' SQL.USER CENTER studytitle RIGHT datevar SKIP 2
BTITLE LEFT filename          CENTER progname   RIGHT 'Page:' FORMAT 09 SQL.PNO 

Select
  LABORATORY,
  TEST_COMPONENT_ID,
  OC_LAB_QUESTION,
  LAB_PANEL
from NCI_LAB_MAPPING
WHERE TEST_COMPONENT_ID in
   (select distinct TEST_COMPONENT_ID FROM NCI_LABS)
and Laboratory in 
(select distinct laboratory from NCI_LABS)
order by OC_LAB_QUESTION;

SPOOL OFF;

CLEAR COLUMNS

