
SET TIME OFF
SET HEADING ON
SET LINESIZE 120
SET PAGESIZE 52
SET TRIMOUT OFF
SET TRIMSPOOL OFF
SET PAUSE OFF
SET WRAP OFF
SET ECHO OFF
SET DOCUMENT OFF
SET VERIFY OFF
SET SHOW OFF
SET FEEDBACK OFF
SET ARRAYSIZE 15
SET NUMWIDTH 10

COLUMN today            NOPRINT NEW_VALUE     datevar

COLUMN 	PT_ID				HEADING "PATIENT ID (LAB)"	FORMAT A20
COLUMN 	NCI_INST_CD			HEADING "NCI INSTITUTION"	FORMAT A20


SELECT TO_CHAR(SYSDATE,'DD-MON-YY HH:MI:SS AM') today FROM DUAL;

SPOOL PATIENT_ID_PTID_VW_DATA;

DEFINE studytitle =  "LAB_LOADER - PATIENT_ID_PTID_VW"
DEFINE filename = "File: PATIENT_ID_PTID_VW_DATA"
DEFINE Progname = "SQl script: PATIENT_ID_PTID_VW_DATA.SQL"
TTITLE LEFT 'User: ' SQL.USER CENTER studytitle RIGHT datevar SKIP 2
BTITLE LEFT filename          CENTER progname   RIGHT 'Page:' FORMAT 09 SQL.PNO 

Select
  PT_ID,
  NCI_INST_CD
from PATIENT_ID_PTID_VW
ORDER BY 1, 2;

SPOOL OFF;

CLEAR COLUMNS


